import { Product, Category, Review } from '@/types/database';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    slug: 'roleti',
    title_ua: 'Ролети',
    title_ru: 'Роллеты',
    description_ua: 'Рулонні та тканинні ролети на вікна будь-яких розмірів. Власне виробництво.',
    image_url: 'https://manov.com.ua/image/catalog/site_img/vr1.webp',
    sort_order: 1,
  },
  {
    id: 'cat-2',
    slug: 'shtori',
    title_ua: 'Штори',
    title_ru: 'Шторы',
    description_ua: 'Рулонні штори, римські, день-ніч та блекаут за індивідуальними розмірами.',
    image_url: 'https://manov.com.ua/image/catalog/site_img/vr2.webp',
    sort_order: 2,
  },
  {
    id: 'cat-3',
    slug: 'zhaluzi',
    title_ua: 'Жалюзі',
    title_ru: 'Жалюзи',
    description_ua: 'Горизонтальні, вертикальні, дерев’яні, бамбукові та алюмінієві жалюзі.',
    image_url: 'https://manov.com.ua/image/catalog/site_img/vr3.webp',
    sort_order: 3,
  },
  {
    id: 'cat-4',
    slug: 'zakryta-sistema',
    title_ua: 'Закрита система',
    title_ru: 'Закрытая система',
    description_ua: 'Ролети з коробом та направляючими для ідеального прилягання до вікна.',
    image_url: 'https://manov.com.ua/image/catalog/site_img/vr4.webp',
    sort_order: 4,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-767',
    slug: 'rulonni_shtory_len_korychnevyj_25_koloriv_pid_vash_rozmir',
    title: 'Рулонні штори LEN Коричневий L-7439',
    sku: 'L-7439',
    category_slug: 'shtori',
    subcategory_slug: 'rulonni',
    base_price: 229,
    old_price: 289,
    price_unit: 'грн',
    min_width: 20,
    max_width: 240,
    min_height: 30,
    max_height: 250,
    base_width: 50,
    base_height: 150,
    price_per_sqm: 390,
    fabric: 'Len (Льон)',
    texture: 'Без малюнка',
    blackout_percent: 40,
    color_name: 'Коричневий',
    color_hex: '#6A4E38',
    available_colors: [
      { id: 'c1', name: 'Коричневий', code: 'L-7439', hex: '#6A4E38', inStock: true },
      { id: 'c2', name: 'Бежевий', code: 'L-7430', hex: '#D7BA9D', inStock: true },
      { id: 'c3', name: 'Графіт', code: 'L-7442', hex: '#4A4C50', inStock: true },
      { id: 'c4', name: 'Пісочний', code: 'L-7435', hex: '#E2CDAB', inStock: true },
      { id: 'c5', name: 'Олива', code: 'L-7438', hex: '#7A845A', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/roller-blind/rb-len-7439-800x800.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/roller-blind/rb-len-7439-800x800.jpg',
      'https://manov.com.ua/image/cache/catalog/%20акто%20/Len/Len%207439-1024x1024.jpg',
      'https://manov.com.ua/image/cache/catalog/des_inter/855/1-560x312.jpg',
      'https://manov.com.ua/image/cache/catalog/des_inter/855/2-560x312.jpg',
      'https://manov.com.ua/image/cache/catalog/des_inter/855/3-560x312.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: true,
    in_stock: true,
    rating: 5.0,
    reviews_count: 23,
    destinations: ['na-kuhnju', 'v-spalnju', 'v-gostinnuju', 'na-balkon', 'v-ofis'],
    description: `Ці рулонні штори коричневого кольору мають велике плетіння, що забезпечить вашому приміщенню затемнення на рівні 40%. Це чудове рішення для кімнат, куди потрапляє не дуже багато сонячного світла, або якщо вимоги до затемнення не високі, при цьому вдається створити достатньо комфортні умови.

Тканина льняна, тому в неї приваблива й унікальна текстура. Система рулонних штор відкрита, тому вони добре вписуються в різні приміщення та стилістику. Ще один плюс для вас у виборі цієї моделі — простота монтажу без специфічного інструменту.`,
    characteristics: {
      'Фактура': 'Без малюнка',
      'Тканина': 'Len',
      'Колір': 'Коричневий',
      'Затемнення': '40%',
      'Система': 'Відкрита Mini',
      'Країна виробник тканини': 'Польща / Німеччина',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-574',
    slug: 'rulonni_shtory_berlin_zelenyj_23_kolory',
    title: 'Рулонні штори Berlin Зелений B-0842',
    sku: 'B-0842',
    category_slug: 'shtori',
    subcategory_slug: 'rulonni',
    base_price: 265,
    old_price: 320,
    price_unit: 'грн',
    min_width: 20,
    max_width: 240,
    min_height: 30,
    max_height: 250,
    base_width: 50,
    base_height: 150,
    price_per_sqm: 420,
    fabric: 'Berlin',
    texture: 'Без малюнка',
    blackout_percent: 55,
    color_name: 'Зелений',
    color_hex: '#2E6F40',
    available_colors: [
      { id: 'cb1', name: 'Зелений', code: 'B-0842', hex: '#2E6F40', inStock: true },
      { id: 'cb2', name: 'Смарагдовий', code: 'B-0845', hex: '#114B36', inStock: true },
      { id: 'cb3', name: 'М\'ятний', code: 'B-0841', hex: '#77BFA2', inStock: true },
      { id: 'cb4', name: 'Білий', code: 'B-0801', hex: '#FFFFFF', inStock: true },
      { id: 'cb5', name: 'Сірий', code: 'B-0810', hex: '#8F949A', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/roller-blind/roller-blind-berlin-0842-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/roller-blind/roller-blind-berlin-0842-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/des_inter/855/1-560x312.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: false,
    in_stock: true,
    rating: 4.9,
    reviews_count: 11,
    destinations: ['na-kuhnju', 'v-detskuju', 'v-spalnju', 'v-ofis'],
    description: `Рулонні штори Berlin відрізняються щільною структурою полотна зі спеціальним пиловідштовхуючим просоченням. Чудово підходять як для вітальні, так і для кухні та дитячої кімнати.`,
    characteristics: {
      'Фактура': 'Без малюнка',
      'Тканина': 'Berlin',
      'Колір': 'Зелений',
      'Затемнення': '55%',
      'Система': 'Відкрита Mini',
      'Країна виробник тканини': 'Німеччина',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-213',
    slug: 'rolety_den_nich_secret_chornyj_5_koloriv_vsi_rozmiry',
    title: 'Ролети День Ніч Secret Чорний DN-208',
    sku: 'DN-208',
    category_slug: 'roleti',
    subcategory_slug: 'den-nich',
    base_price: 529,
    old_price: 649,
    price_unit: 'грн',
    min_width: 25,
    max_width: 250,
    min_height: 30,
    max_height: 260,
    base_width: 50,
    base_height: 150,
    price_per_sqm: 850,
    fabric: 'Secret Day-Night',
    texture: 'Смугастий (День-Ніч)',
    blackout_percent: 75,
    color_name: 'Чорний',
    color_hex: '#1E1E1E',
    available_colors: [
      { id: 'cdn1', name: 'Чорний', code: 'DN-208', hex: '#1E1E1E', inStock: true },
      { id: 'cdn2', name: 'Шоколадний', code: 'DN-205', hex: '#3E2723', inStock: true },
      { id: 'cdn3', name: 'Графіт', code: 'DN-209', hex: '#37474F', inStock: true },
      { id: 'cdn4', name: 'Білий', code: 'DN-201', hex: '#FAFAFA', inStock: true },
      { id: 'cdn5', name: 'Кремовий', code: 'DN-203', hex: '#FFF8E1', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/day-night/secret-208-dn-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/day-night/secret-208-dn-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: true,
    in_stock: true,
    rating: 4.8,
    reviews_count: 7,
    destinations: ['v-spalnju', 'v-gostinnuju', 'v-ofis', 'na-mansardu'],
    description: `Ролети День-Ніч (Зебра) Secret дозволяють тонко регулювати освітлення у приміщенні за рахунок подвійного шару тканини з чергуванням прозорих та непрозорих смуг.`,
    characteristics: {
      'Фактура': 'День-Ніч',
      'Тканина': 'Secret',
      'Колір': 'Чорний',
      'Затемнення': 'до 75%',
      'Система': 'Mini День-Ніч',
      'Країна виробник тканини': 'Польща',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-231',
    slug: 'rolety_den_nich_akvarel_biryuzovyj_13_koloriv_vsi_rozmiry',
    title: 'Ролети День Ніч Акварель Бірюзовий DN-1208',
    sku: 'DN-1208',
    category_slug: 'roleti',
    subcategory_slug: 'den-nich',
    base_price: 529,
    old_price: 599,
    price_unit: 'грн',
    min_width: 25,
    max_width: 240,
    min_height: 30,
    max_height: 250,
    base_width: 50,
    base_height: 150,
    price_per_sqm: 850,
    fabric: 'Акварель День-Ніч',
    texture: 'Смугастий (День-Ніч)',
    blackout_percent: 65,
    color_name: 'Бірюзовий',
    color_hex: '#16A085',
    available_colors: [
      { id: 'ca1', name: 'Бірюзовий', code: 'DN-1208', hex: '#16A085', inStock: true },
      { id: 'ca2', name: 'Блакитний', code: 'DN-1204', hex: '#3498DB', inStock: true },
      { id: 'ca3', name: 'Лавандовий', code: 'DN-1211', hex: '#9B59B6', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: false,
    in_stock: true,
    rating: 5.0,
    reviews_count: 7,
    destinations: ['na-kuhnju', 'v-detskuju', 'v-spalnju'],
    description: `Оригінальні ролети День-Ніч з колекції Акварель створюють свіжий та сучасний вигляд віконного простору з можливістю плавного затемнення.`,
    characteristics: {
      'Фактура': 'День-Ніч',
      'Тканина': 'Акварель',
      'Колір': 'Бірюзовий',
      'Затемнення': '65%',
      'Система': 'Відкрита День-Ніч',
      'Країна виробник тканини': 'Польща',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-1203',
    slug: 'goryzontalni_zhalyuzi_bili_900',
    title: 'Горизонтальні жалюзі Білі 451 Classic',
    sku: 'J-900',
    category_slug: 'zhaluzi',
    subcategory_slug: 'gorizontalnie_zhaluzi',
    base_price: 219,
    old_price: 260,
    price_unit: 'грн',
    min_width: 25,
    max_width: 250,
    min_height: 30,
    max_height: 300,
    base_width: 50,
    base_height: 140,
    price_per_sqm: 350,
    fabric: 'Алюміній 25мм',
    texture: 'Гладкий метал',
    blackout_percent: 85,
    color_name: 'Білий',
    color_hex: '#FFFFFF',
    available_colors: [
      { id: 'cj1', name: 'Білий 451', code: 'J-451', hex: '#FFFFFF', inStock: true },
      { id: 'cj2', name: 'Сріблястий металік', code: 'J-452', hex: '#C0C0C0', inStock: true },
      { id: 'cj3', name: 'Бежевий', code: 'J-453', hex: '#F5F5DC', inStock: true },
      { id: 'cj4', name: 'Антрацит', code: 'J-454', hex: '#2C3E50', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: true,
    in_stock: true,
    rating: 4.9,
    reviews_count: 16,
    destinations: ['na-kuhnju', 'na-balkon', 'v-ofis', 'v-spalnju'],
    description: `Класичні алюмінієві горизонтальні жалюзі 25 мм білого кольору. Стійкі до вологи, перепадів температур та прямого сонячного проміння. Ідеально підходять для кухонь, балконів, ванних кімнат та офісів.`,
    characteristics: {
      'Матеріал': 'Алюмінієва стрічка 25 мм',
      'Колір': 'Білий 451',
      'Управління': 'Трость + шнур',
      'Захист від світла': 'до 85%',
      'Країна виробник стрічки': 'Польща (Magnum)',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-90',
    slug: 'rulonni_shtory_blekaut_umbra_grafitovyj_8_koloriv_vsi_rozmiry',
    title: 'Рулонні штори Блекаут Umbra Графітовий BO-880',
    sku: 'BO-880',
    category_slug: 'shtori',
    subcategory_slug: 'blekhaut',
    base_price: 549,
    old_price: 680,
    price_unit: 'грн',
    min_width: 25,
    max_width: 240,
    min_height: 30,
    max_height: 250,
    base_width: 50,
    base_height: 150,
    price_per_sqm: 890,
    fabric: 'Umbra Blackout 100%',
    texture: 'Без малюнка (Світлонепроникний)',
    blackout_percent: 100,
    color_name: 'Графітовий',
    color_hex: '#2B2E33',
    available_colors: [
      { id: 'cu1', name: 'Графітовий', code: 'BO-880', hex: '#2B2E33', inStock: true },
      { id: 'cu2', name: 'Чорний глибокий', code: 'BO-885', hex: '#111111', inStock: true },
      { id: 'cu3', name: 'Світло-сірий', code: 'BO-870', hex: '#BDC3C7', inStock: true },
      { id: 'cu4', name: 'Шоколад', code: 'BO-875', hex: '#4A2E18', inStock: true },
      { id: 'cu5', name: 'Темно-синій', code: 'BO-890', hex: '#1B263B', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: true,
    in_stock: true,
    rating: 5.0,
    reviews_count: 2,
    destinations: ['v-spalnju', 'v-detskuju', 'v-ofis', 'na-mansardu'],
    description: `100% захист від сонячного світла та спеки! Тканина Umbra Blackout має багатошарову прогумовану основу, яка повністю блокує проникнення світла у кімнату навіть у найяскравіший сонячний полудень.`,
    characteristics: {
      'Фактура': 'Блекаут 100%',
      'Тканина': 'Umbra Blackout',
      'Колір': 'Графітовий',
      'Затемнення': '100%',
      'Теплоізоляція': 'Висока (відбиває тепло)',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-1517',
    slug: 'bambukovi_zhalyuzi_25_mm_kolir_25',
    title: 'Бамбукові жалюзі 25 мм Sand 736103',
    sku: 'BAM-25-25',
    category_slug: 'zhaluzi',
    subcategory_slug: 'bambukovi_zhalyuzi',
    base_price: 4999,
    price_unit: 'грн',
    min_width: 30,
    max_width: 210,
    min_height: 40,
    max_height: 280,
    base_width: 60,
    base_height: 140,
    price_per_sqm: 4800,
    fabric: 'Натуральний бамбук 25мм',
    texture: 'Деревна натуральна',
    blackout_percent: 85,
    color_name: 'Пісочний (Sand)',
    color_hex: '#D1B48C',
    available_colors: [
      { id: 'cbm1', name: 'Пісочний Sand', code: 'BAM-25', hex: '#D1B48C', inStock: true },
      { id: 'cbm2', name: 'Натуральний бамбук', code: 'BAM-01', hex: '#E5C287', inStock: true },
      { id: 'cbm3', name: 'Махагон', code: 'BAM-12', hex: '#4E1609', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/%20145254/%20жалюзи%2025мм/25mm%20Цвет%2025-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/%20145254/%20жалюзи%2025мм/25mm%20Цвет%2025-318x480.jpg',
    ],
    is_popular: false,
    is_new: true,
    is_offer_of_day: false,
    in_stock: true,
    rating: 5.0,
    reviews_count: 3,
    destinations: ['v-gostinnuju', 'v-spalnju', 'v-ofis'],
    description: `Преміальні жалюзі з натурального пресованого бамбука. Легкі, екологічно чисті, мають неповторну фактуру дерева та високу стійкість до вологості.`,
    characteristics: {
      'Матеріал': '100% натуральний бамбук',
      'Ширина ламелі': '25 мм',
      'Колір': 'Sand 25',
      'Покриття': 'Вологозахисний матовий лак',
      'Гарантія': '24 місяці',
    },
  },
  {
    id: 'prod-1508',
    slug: 'derev_yani_zhalyuzi_50_mm_kolir_17',
    title: 'Дерев\'яні жалюзі 50 мм Natural A19',
    sku: 'WOOD-50-17',
    category_slug: 'zhaluzi',
    subcategory_slug: 'derevyani',
    base_price: 4399,
    price_unit: 'грн',
    min_width: 40,
    max_width: 240,
    min_height: 40,
    max_height: 300,
    base_width: 60,
    base_height: 150,
    price_per_sqm: 4200,
    fabric: 'Канадська липа (Basswood) 50мм',
    texture: 'Масив натурального дерева',
    blackout_percent: 90,
    color_name: 'Natural Wood',
    color_hex: '#A0522D',
    available_colors: [
      { id: 'cw1', name: 'Natural A19', code: 'WOOD-17', hex: '#A0522D', inStock: true },
      { id: 'cw2', name: 'Білий глянець', code: 'WOOD-01', hex: '#FFFFFF', inStock: true },
      { id: 'cw3', name: 'Венге', code: 'WOOD-41', hex: '#2B1B17', inStock: true },
      { id: 'cw4', name: 'Горіх', code: 'WOOD-22', hex: '#5C381E', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/%20145254/%2023%20Деревянные%20жалюзи%2025%20мм/50mm%20Цвет%2017-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/%20145254/%2023%20Деревянные%20жалюзи%2025%20мм/50mm%20Цвет%2017-318x480.jpg',
    ],
    is_popular: false,
    is_new: true,
    is_offer_of_day: false,
    in_stock: true,
    rating: 5.0,
    reviews_count: 5,
    destinations: ['v-gostinnuju', 'v-spalnju', 'v-ofis'],
    description: `Розкішні жалюзі з масиву дерева (американська липа Basswood) з ламелями шириною 50 мм. Створюють благородну атмосферу в інтер'єрі кабінету, вітальні або спальні.`,
    characteristics: {
      'Матеріал': 'Масив натуральної липи',
      'Ширина ламелі': '50 мм',
      'Колір': 'Natural A19',
      'Тасьма': 'Шнурова або тканинна драбинка',
      'Гарантія': '24 місяці',
    },
  },
  {
    id: 'prod-741',
    slug: 'rulonni_iz_zakrytoyu_systemoyu_len_0881',
    title: 'Рулонні штори із закритою системою Len 0881',
    sku: 'CS-LEN-0881',
    category_slug: 'zakryta-sistema',
    subcategory_slug: 'rulonni_zakritaya_sistema',
    base_price: 559,
    old_price: 690,
    price_unit: 'грн',
    min_width: 25,
    max_width: 180,
    min_height: 30,
    max_height: 240,
    base_width: 50,
    base_height: 140,
    price_per_sqm: 780,
    fabric: 'Len Закрита система',
    texture: 'Лляна фактура',
    blackout_percent: 50,
    color_name: 'Бежевий льон',
    color_hex: '#C8AD8D',
    available_colors: [
      { id: 'ccl1', name: 'Бежевий', code: 'CS-0881', hex: '#C8AD8D', inStock: true },
      { id: 'ccl2', name: 'Білий', code: 'CS-0880', hex: '#FFFFFF', inStock: true },
      { id: 'ccl3', name: 'Капучино', code: 'CS-0885', hex: '#8B7355', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: false,
    in_stock: true,
    rating: 4.9,
    reviews_count: 8,
    destinations: ['v-spalnju', 'na-kuhnju', 'v-detskuju', 'na-balkon'],
    description: `Закрита касетна система Uni з алюмінієвим коробом та плоскими/П-подібними направляючими. Полотно надійно зафіксоване вздовж склопакета, виключаючи провисання при відкриванні стулки на провітрювання.`,
    characteristics: {
      'Система': 'Закрита касета Uni-1 / Uni-2',
      'Матеріал короба': 'Алюміній (білий, коричневий, антрацит, золотий дуб)',
      'Тканина': 'Len',
      'Затемнення': '50%',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-1656',
    slug: 'plise_duo_ecoro_graphite',
    title: 'Штори Плісе Duo Ecoro Graphite PL-502',
    sku: 'PL-502',
    category_slug: 'shtori',
    subcategory_slug: 'plise',
    base_price: 1199,
    old_price: 1390,
    price_unit: 'грн',
    min_width: 20,
    max_width: 160,
    min_height: 30,
    max_height: 220,
    base_width: 50,
    base_height: 130,
    price_per_sqm: 1750,
    fabric: 'Плісе Duo стільникове',
    texture: 'Плісирована фактура 20мм',
    blackout_percent: 80,
    color_name: 'Graphite',
    color_hex: '#3E424B',
    available_colors: [
      { id: 'cpl1', name: 'Graphite', code: 'PL-502', hex: '#3E424B', inStock: true },
      { id: 'cpl2', name: 'White Silk', code: 'PL-501', hex: '#F7F7F7', inStock: true },
      { id: 'cpl3', name: 'Sand Cream', code: 'PL-503', hex: '#E7D9C3', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/%20%2012%20123123/plicce/graphite-318x480.png',
    images: [
      'https://manov.com.ua/image/cache/catalog/%20%2012%20123123/plicce/graphite-318x480.png',
    ],
    is_popular: true,
    is_new: true,
    is_offer_of_day: false,
    in_stock: true,
    rating: 5.0,
    reviews_count: 4,
    destinations: ['na-kuhnju', 'v-spalnju', 'v-gostinnuju', 'na-mansardu'],
    description: `Штори Плісе Duo з можливістю відкривання як зверху вниз, так і знизу вгору (система день-ніч / подвійне управління). Ідеально для нестандартних, мансардних та поворотних вікон.`,
    characteristics: {
      'Тип тканини': 'Плісе з сотовою структурою (Duo)',
      'Ширина складки': '20 мм',
      'Управління': 'Ручка на профілі (Top-Down / Bottom-Up)',
      'Затемнення': '80%',
      'Гарантія': '18 місяців',
    },
  },
  {
    id: 'prod-1608',
    slug: 'vertykalni_zhalyuzi_127mm_line-6',
    title: 'Вертикальні жалюзі 127мм Line Сірий V-8013',
    sku: 'V-8013',
    category_slug: 'zhaluzi',
    subcategory_slug: 'vertikalnie_zhaluzi',
    base_price: 499,
    old_price: 580,
    price_unit: 'грн',
    min_width: 50,
    max_width: 400,
    min_height: 50,
    max_height: 400,
    base_width: 100,
    base_height: 180,
    price_per_sqm: 450,
    fabric: 'Line 127 мм',
    texture: 'Рельєфна тканинна',
    blackout_percent: 60,
    color_name: 'Сірий',
    color_hex: '#8C9298',
    available_colors: [
      { id: 'cv1', name: 'Сірий', code: 'V-8013', hex: '#8C9298', inStock: true },
      { id: 'cv2', name: 'Бежевий', code: 'V-8010', hex: '#D2B48C', inStock: true },
      { id: 'cv3', name: 'Блакитний', code: 'V-8015', hex: '#87CEEB', inStock: true },
      { id: 'cv4', name: 'Білий', code: 'V-8001', hex: '#FFFFFF', inStock: true },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/%20%2012%20123123/vertikalni/8013-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/%20%2012%20123123/vertikalni/8013-318x480.jpg',
    ],
    is_popular: true,
    is_new: true,
    is_offer_of_day: false,
    in_stock: true,
    rating: 4.8,
    reviews_count: 6,
    destinations: ['v-ofis', 'v-gostinnuju', 'na-balkon'],
    description: `Тканинні вертикальні жалюзі з ламелями 127 мм. Оптимальне рішення для великих віконних прорізів, офісів, навчальних закладів та просторих віталень.`,
    characteristics: {
      'Ширина ламелі': '127 мм',
      'Тканина': 'Line',
      'Колір': 'Сірий',
      'Карниз': 'Алюмінієвий посилений білий',
      'Гарантія': '12 місяців',
    },
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-767',
    author_name: 'Оксана Мельник',
    city: 'Київ',
    rating: 5,
    comment: 'Замовляли штори Len на всі вікна в трикімнатну квартиру. Якість тканини чудова, розміри підійшли міліметр у міліметр! Встановили самі за інструкцією за півгодини. Дуже дякую менеджеру за терплячу консультацію.',
    created_at: '2026-05-12T14:30:00Z',
  },
  {
    id: 'rev-2',
    product_id: 'prod-767',
    author_name: 'Володимир',
    city: 'Дніпро',
    rating: 5,
    comment: 'Купую тут вже вдруге. Перший раз брав жалюзі на балкон 2 роки тому — служать відмінно. Зараз взяли рулонні штори в спальню. Відправили Новою Поштою швидко.',
    created_at: '2026-06-04T10:15:00Z',
  },
  {
    id: 'rev-3',
    product_id: 'prod-213',
    author_name: 'Ірина Гриценко',
    city: 'Львів',
    rating: 5,
    comment: 'День-Ніч Secret виглядають дуже стильно і дорого! Чорний колір у вітальні виглядає дуже ефектно. Регулювати світло неймовірно зручно.',
    created_at: '2026-06-20T16:45:00Z',
  },
  {
    id: 'rev-4',
    product_id: 'prod-90',
    author_name: 'Андрій К.',
    city: 'Одеса',
    rating: 5,
    comment: 'Блекаут 100% дійсно не пропускає ані промінчика! У спеку в кімнаті набагато прохолодніше. За таку ціну якість супер.',
    created_at: '2026-07-01T11:20:00Z',
  },
];

export const FAQ_ITEMS = [
  {
    question: 'Скільки часу займе виготовлення?',
    answer: 'Виготовлення займає від 2 до 4 робочих днів, залежно від типу виробу та завантаженості виробництва.',
  },
  {
    question: 'Чим жалюзі на замовлення відрізняються від готових з гіпермаркету?',
    answer: 'Готові вироби обмежені стандартними розмірами (і часто не підходять по ширині чи висять задовгими). На замовлення ми виготовляємо жалюзі за вашими точними міліметровими розмірами, тому ви не переплачуєте за надлишок і отримуєте ідеальне прилягання.',
  },
  {
    question: 'Як самостійно порахувати вартість виробу?',
    answer: 'Ви можете скористатися нашим онлайн-калькулятором на сторінці будь-якого товару: введіть точну ширину та висоту в сантиметрах, оберіть параметри — ціна розрахується миттєво.',
  },
  {
    question: 'Як зробити замовлення?',
    answer: 'Оберіть потрібний товар, вкажіть розміри та колір, додайте в кошик або натисніть "Купити в 1 клік". Також можна зателефонувати нам чи написати в Telegram / Viber.',
  },
  {
    question: 'Чи є у вас послуга заміру та монтажу?',
    answer: 'Ми — виробник і надсилаємо готові до встановлення вироби по всій Україні. На нашому сайті є детальні покрокові відео- та фотоінструкції ("Замір" і "Монтаж"), за якими будь-хто легко зможе встановити ролети всього за 10-15 хвилин за допомогою звичайної викрутки.',
  },
  {
    question: 'Хто виробник фурнітури та тканин?',
    answer: 'Ми використовуємо високоякісну польську фурнітуру Besta та тканини виробництва Німеччини, Польщі, Італії та Туреччини зі спеціальними пило- та вологовідштовхуючими просоченнями.',
  },
  {
    question: 'Чи є гарантія на продукцію?',
    answer: 'Так, ми надаємо офіційну гарантію виробника 12 місяців на всі механізми та вироби.',
  },
];

export const CITIES_LIST = [
  { name: 'Для всіх міст', slug: 'all' },
  { name: 'Київ', slug: 'kyiv' },
  { name: 'Вінниця', slug: 'vinnitsya' },
  { name: 'Дніпро', slug: 'dnipro' },
  { name: 'Запоріжжя', slug: 'zaporizhzhya' },
  { name: 'Львів', slug: 'lviv' },
  { name: 'Одеса', slug: 'odesa' },
  { name: 'Харків', slug: 'harkiv' },
  { name: 'Черкаси', slug: 'cherkasi' },
  { name: 'Полтава', slug: 'poltawa' },
  { name: 'Івано-Франківськ', slug: 'ivano-frankivsk' },
  { name: 'Тернопіль', slug: 'ternopil' },
  { name: 'Рівне', slug: 'rivne' },
  { name: 'Хмельницький', slug: 'khmelnytskyi' },
  { name: 'Чернівці', slug: 'chernivtsi' },
  { name: 'Житомир', slug: 'zhytomyr' },
  { name: 'Суми', slug: 'sumy' },
  { name: 'Миколаїв', slug: 'mykolaiv' },
  { name: 'Кривий Ріг', slug: 'kryvyi-rih' },
];
