import { Product, Category, Review } from '@/types/database';

export const CATEGORIES_LIST: Category[] = [
  {
    id: 'cat-roleti',
    slug: 'roleti',
    title_ua: 'Ролети на вікна',
    description_ua: 'Тканинні ролети відкритого та закритого типу від виробника в Дніпрі',
    icon: 'RollerBlind',
    image_url: 'https://manov.com.ua/image/cache/catalog/roller-blind/rb-len-7439-800x800.jpg',
  },
  {
    id: 'cat-shtori',
    slug: 'shtori',
    title_ua: 'Рулонні та римські штори',
    description_ua: 'Штори блекаут, день-ніч та плісе для спальні, вітальні, дитячої',
    icon: 'Curtains',
    image_url: 'https://manov.com.ua/image/cache/catalog/day-night/secret-208-dn-318x480.jpg',
  },
  {
    id: 'cat-zhaluzi',
    slug: 'zhaluzi',
    title_ua: 'Жалюзі',
    description_ua: 'Горизонтальні алюмінієві 25 мм та вертикальні тканинні 89/127 мм жалюзі',
    icon: 'Blinds',
    image_url: 'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg',
  },
  {
    id: 'cat-zakryta-sistema',
    slug: 'zakryta-sistema',
    title_ua: 'Закрита система',
    description_ua: 'Касетні ролети з направляючими для пластикових вікон',
    icon: 'Box',
    image_url: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
  },
];

export const MOCK_CATEGORIES = CATEGORIES_LIST;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-767',
    slug: 'rulonni_shtory_len_korychnevyj_14_koloriv_vsi_rozmiry',
    title: 'Рулонні штори Len Коричневий L-7439',
    sku: 'L-7439',
    category_slug: 'roleti',
    subcategory_slug: 'rulonni',
    base_price: 229,
    old_price: 289,
    price_unit: 'грн',
    min_width: 20,
    max_width: 240,
    min_height: 30,
    max_height: 250,
    base_width: 50,
    base_height: 150,
    price_per_sqm: 390,
    fabric: 'Len (Льон)',
    texture: 'Без малюнка',
    blackout_percent: 40,
    color_name: 'Коричневий',
    color_hex: '#6A4E38',
    available_colors: [
      { id: 'c1', name: 'Коричневий', code: 'L-7439', hex: '#6A4E38', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/rb-len-7439-800x800.jpg' },
      { id: 'c2', name: 'Бежевий', code: 'L-7430', hex: '#D7BA9D', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg' },
      { id: 'c3', name: 'Графіт', code: 'L-7442', hex: '#4A4C50', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg' },
      { id: 'c4', name: 'Пісочний', code: 'L-7435', hex: '#E2CDAB', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/%20145254/%20жалюзи%2025мм/25mm%20Цвет%2025-318x480.jpg' },
      { id: 'c5', name: 'Олива', code: 'L-7438', hex: '#7A845A', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/roller-blind-berlin-0842-318x480.jpg' },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/roller-blind/rb-len-7439-800x800.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/roller-blind/rb-len-7439-800x800.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/%20145254/%20жалюзи%2025мм/25mm%20Цвет%2025-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/roller-blind-berlin-0842-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: true,
    in_stock: true,
    rating: 5.0,
    reviews_count: 23,
    destinations: ['na-kuhnju', 'v-spalnju', 'v-gostinnuju', 'na-balkon', 'v-ofis'],
    description: `Ці рулонні штори коричневого кольору мають велике плетіння, що забезпечить вашому приміщенню затемнення на рівні 40%. Це чудове рішення для кімнат, куди потрапляє не дуже багато сонячного світла, або якщо вимоги до затемнення не високі.

Тканина льняна, тому в неї приваблива й унікальна текстура. Система рулонних штор відкрита, тому вони добре вписуються в різні приміщення та стилістику. Ще один плюс для вас — простота монтажу без специфічного інструменту.`,
    characteristics: {
      'Фактура': 'Без малюнка',
      'Тканина': 'Len',
      'Колір': 'Коричневий',
      'Затемнення': '40%',
      'Система': 'Відкрита Mini',
      'Країна виробник тканини': 'Польща / Німеччина',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-574',
    slug: 'rulonni_shtory_berlin_zelenyj_23_kolory',
    title: 'Рулонні штори Berlin Зелений B-0842',
    sku: 'B-0842',
    category_slug: 'shtori',
    subcategory_slug: 'rulonni',
    base_price: 265,
    old_price: 320,
    price_unit: 'грн',
    min_width: 20,
    max_width: 240,
    min_height: 30,
    max_height: 250,
    base_width: 50,
    base_height: 150,
    price_per_sqm: 420,
    fabric: 'Berlin',
    texture: 'Без малюнка',
    blackout_percent: 55,
    color_name: 'Зелений',
    color_hex: '#2E6F40',
    available_colors: [
      { id: 'cb1', name: 'Зелений', code: 'B-0842', hex: '#2E6F40', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/roller-blind-berlin-0842-318x480.jpg' },
      { id: 'cb2', name: 'Смарагдовий', code: 'B-0845', hex: '#114B36', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg' },
      { id: 'cb3', name: 'М\'ятний', code: 'B-0841', hex: '#77BFA2', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg' },
      { id: 'cb4', name: 'Білий', code: 'B-0801', hex: '#FFFFFF', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg' },
      { id: 'cb5', name: 'Сірий', code: 'B-0810', hex: '#8F949A', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg' },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/roller-blind/roller-blind-berlin-0842-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/roller-blind/roller-blind-berlin-0842-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: false,
    in_stock: true,
    rating: 4.9,
    reviews_count: 11,
    destinations: ['na-kuhnju', 'v-detskuju', 'v-spalnju', 'v-ofis'],
    description: `Рулонні штори Berlin відрізняються щільною структурою полотна зі спеціальним пиловідштовхуючим просоченням. Чудово підходять як для вітальні, так і для кухні та дитячої кімнати.`,
    characteristics: {
      'Фактура': 'Без малюнка',
      'Тканина': 'Berlin',
      'Колір': 'Зелений',
      'Затемнення': '55%',
      'Система': 'Відкрита Mini',
      'Країна виробник тканини': 'Німеччина',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-213',
    slug: 'rolety_den_nich_secret_chornyj_5_koloriv_vsi_rozmiry',
    title: 'Ролети День Ніч Secret Чорний DN-208',
    sku: 'DN-208',
    category_slug: 'roleti',
    subcategory_slug: 'den-nich',
    base_price: 529,
    old_price: 649,
    price_unit: 'грн',
    min_width: 25,
    max_width: 250,
    min_height: 30,
    max_height: 260,
    base_width: 50,
    base_height: 150,
    price_per_sqm: 850,
    fabric: 'Secret Day-Night',
    texture: 'Смугастий (День-Ніч)',
    blackout_percent: 75,
    color_name: 'Чорний',
    color_hex: '#1E1E1E',
    available_colors: [
      { id: 'cdn1', name: 'Чорний', code: 'DN-208', hex: '#1E1E1E', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/day-night/secret-208-dn-318x480.jpg' },
      { id: 'cdn2', name: 'Шоколадний', code: 'DN-205', hex: '#3E2723', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg' },
      { id: 'cdn3', name: 'Графіт', code: 'DN-209', hex: '#37474F', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg' },
      { id: 'cdn4', name: 'Білий', code: 'DN-201', hex: '#FAFAFA', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg' },
      { id: 'cdn5', name: 'Кремовий', code: 'DN-203', hex: '#FFF8E1', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg' },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/day-night/secret-208-dn-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/day-night/secret-208-dn-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: true,
    in_stock: true,
    rating: 4.8,
    reviews_count: 7,
    destinations: ['v-spalnju', 'v-gostinnuju', 'v-ofis', 'na-mansardu'],
    description: `Ролети День-Ніч (Зебра) Secret дозволяють тонко регулювати освітлення у приміщенні за рахунок подвійного шару тканини з чергуванням прозорих та непрозорих смуг.`,
    characteristics: {
      'Фактура': 'День-Ніч',
      'Тканина': 'Secret',
      'Колір': 'Чорний',
      'Затемнення': 'до 75%',
      'Система': 'Mini День-Ніч',
      'Країна виробник тканини': 'Польща',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-231',
    slug: 'rolety_den_nich_akvarel_biryuzovyj_13_koloriv_vsi_rozmiry',
    title: 'Ролети День Ніч Акварель Бірюзовий DN-1208',
    sku: 'DN-1208',
    category_slug: 'roleti',
    subcategory_slug: 'den-nich',
    base_price: 529,
    old_price: 599,
    price_unit: 'грн',
    min_width: 25,
    max_width: 240,
    min_height: 30,
    max_height: 250,
    base_width: 50,
    base_height: 150,
    price_per_sqm: 850,
    fabric: 'Акварель День-Ніч',
    texture: 'Смугастий (День-Ніч)',
    blackout_percent: 65,
    color_name: 'Бірюзовий',
    color_hex: '#16A085',
    available_colors: [
      { id: 'ca1', name: 'Бірюзовий', code: 'DN-1208', hex: '#16A085', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg' },
      { id: 'ca2', name: 'Блакитний', code: 'DN-1204', hex: '#3498DB', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/roller-blind-berlin-0842-318x480.jpg' },
      { id: 'ca3', name: 'Лавандовий', code: 'DN-1211', hex: '#9B59B6', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg' },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/roller-blind-berlin-0842-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: false,
    in_stock: true,
    rating: 5.0,
    reviews_count: 7,
    destinations: ['na-kuhnju', 'v-detskuju', 'v-spalnju'],
    description: `Ніжні пастельні смуги тканини Акварель у бірюзових та блакитних тонах. Створюють легкість та свіжість у будь-якому інтер'єрі.`,
    characteristics: {
      'Фактура': 'День-Ніч',
      'Тканина': 'Акварель',
      'Колір': 'Бірюзовий',
      'Затемнення': '65%',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-1203',
    slug: 'goryzontalni_zhalyuzi_bili_900',
    title: 'Горизонтальні жалюзі Білі 451 Classic',
    sku: 'J-900',
    category_slug: 'zhaluzi',
    subcategory_slug: 'gorizontalnie_zhaluzi',
    base_price: 219,
    old_price: 260,
    price_unit: 'грн',
    min_width: 25,
    max_width: 250,
    min_height: 30,
    max_height: 300,
    base_width: 50,
    base_height: 140,
    price_per_sqm: 350,
    fabric: 'Алюміній 25мм',
    texture: 'Гладкий метал',
    blackout_percent: 85,
    color_name: 'Білий',
    color_hex: '#FFFFFF',
    available_colors: [
      { id: 'cj1', name: 'Білий 451', code: 'J-451', hex: '#FFFFFF', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg' },
      { id: 'cj2', name: 'Сріблястий металік', code: 'J-452', hex: '#C0C0C0', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg' },
      { id: 'cj3', name: 'Бежевий', code: 'J-453', hex: '#F5F5DC', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg' },
      { id: 'cj4', name: 'Антрацит', code: 'J-454', hex: '#2C3E50', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/day-night/secret-208-dn-318x480.jpg' },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/day-night/secret-208-dn-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: true,
    in_stock: true,
    rating: 4.9,
    reviews_count: 16,
    destinations: ['na-kuhnju', 'na-balkon', 'v-ofis', 'v-spalnju'],
    description: `Класичні алюмінієві горизонтальні жалюзі 25 мм білого кольору. Стійкі до вологи, перепадів температур та прямого сонячного проміння.`,
    characteristics: {
      'Матеріал': 'Алюмінієва стрічка 25 мм',
      'Колір': 'Білий 451',
      'Управління': 'Трость + шнур',
      'Захист від світла': 'до 85%',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-90',
    slug: 'rulonni_shtory_blekaut_umbra_grafitovyj_8_koloriv_vsi_rozmiry',
    title: 'Рулонні штори Блекаут Umbra Графітовий BO-880',
    sku: 'BO-880',
    category_slug: 'shtori',
    subcategory_slug: 'blekhaut',
    base_price: 549,
    old_price: 680,
    price_unit: 'грн',
    min_width: 25,
    max_width: 240,
    min_height: 30,
    max_height: 250,
    base_width: 50,
    base_height: 150,
    price_per_sqm: 890,
    fabric: 'Umbra Blackout 100%',
    texture: 'Без малюнка (Світлонепроникний)',
    blackout_percent: 100,
    color_name: 'Графітовий',
    color_hex: '#2B2E33',
    available_colors: [
      { id: 'cu1', name: 'Графітовий', code: 'BO-880', hex: '#2B2E33', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg' },
      { id: 'cu2', name: 'Чорний глибокий', code: 'BO-885', hex: '#111111', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/day-night/secret-208-dn-318x480.jpg' },
      { id: 'cu3', name: 'Світло-сірий', code: 'BO-870', hex: '#BDC3C7', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg' },
      { id: 'cu4', name: 'Шоколад', code: 'BO-875', hex: '#4A2E18', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/rb-len-7439-800x800.jpg' },
      { id: 'cu5', name: 'Темно-синій', code: 'BO-890', hex: '#1B263B', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg' },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/blackout/roller-blind/rb-Umbra-BO-graphity-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/day-night/secret-208-dn-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/rb-len-7439-800x800.jpg',
      'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: true,
    in_stock: true,
    rating: 5.0,
    reviews_count: 2,
    destinations: ['v-spalnju', 'v-detskuju', 'v-ofis', 'na-mansardu'],
    description: `100% захист від сонячного світла та спеки! Тканина Umbra Blackout має багатошарову прогумовану основу, яка повністю блокує проникнення світла у кімнату.`,
    characteristics: {
      'Фактура': 'Блекаут 100%',
      'Тканина': 'Umbra Blackout',
      'Колір': 'Графітовий',
      'Затемнення': '100%',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-1517',
    slug: 'zhalyuzi_vertikalni_tkanynni_89_mm',
    title: 'Вертикальні тканинні жалюзі Line 89 мм',
    sku: 'VERT-89-01',
    category_slug: 'zhaluzi',
    subcategory_slug: 'vertikalnie_zhaluzi',
    base_price: 480,
    price_unit: 'грн',
    min_width: 40,
    max_width: 350,
    min_height: 50,
    max_height: 350,
    base_width: 100,
    base_height: 150,
    price_per_sqm: 480,
    fabric: 'Тканина Line 89мм',
    texture: 'Тканинна фактура',
    blackout_percent: 60,
    color_name: 'Світло-сірий',
    color_hex: '#D1D5DB',
    available_colors: [
      { id: 'cv1', name: 'Світло-сірий', code: 'V-01', hex: '#D1D5DB', inStock: true, image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80' },
      { id: 'cv2', name: 'Бежевий пісок', code: 'V-02', hex: '#E5D9C5', inStock: true, image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80' },
      { id: 'cv3', name: 'Білий сніг', code: 'V-03', hex: '#FFFFFF', inStock: true, image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80' },
    ],
    main_image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: false,
    in_stock: true,
    rating: 4.9,
    reviews_count: 8,
    destinations: ['v-ofis', 'v-gostinnuju', 'na-balkon'],
    description: `Вертикальні тканинні жалюзі з ламелями 89 мм. Ідеальне рішення для великих вікон, офісів, кабінетів та просторих приміщень.`,
    characteristics: {
      'Матеріал': '100% поліестер із пиловідштовхувальним просоченням',
      'Ширина ламелі': '89 мм',
      'Керування': 'Ланцюжок та шнур керування',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-1508',
    slug: 'gorizontalni_zhalyuzi_venus_25_mm',
    title: 'Горизонтальні жалюзі Venus 25 мм на стулку',
    sku: 'VENUS-25-01',
    category_slug: 'zhaluzi',
    subcategory_slug: 'gorizontalnie_zhaluzi',
    base_price: 540,
    price_unit: 'грн',
    min_width: 30,
    max_width: 200,
    min_height: 40,
    max_height: 220,
    base_width: 60,
    base_height: 140,
    price_per_sqm: 540,
    fabric: 'Алюміній Venus 25мм',
    texture: 'Алюмінієвий / Металік',
    blackout_percent: 85,
    color_name: 'Білий Classic',
    color_hex: '#FFFFFF',
    available_colors: [
      { id: 'cven1', name: 'Білий Classic', code: 'VEN-01', hex: '#FFFFFF', inStock: true, image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80' },
      { id: 'cven2', name: 'Сріблястий Металік', code: 'VEN-02', hex: '#A8B0B8', inStock: true, image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80' },
    ],
    main_image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: false,
    in_stock: true,
    rating: 4.8,
    reviews_count: 6,
    destinations: ['na-kuhnju', 'na-balkon', 'v-ofis'],
    description: `Компактні алюмінієві жалюзі системи Venus, що встановлюються впритул до склопакета стулки вікна з монокомандним керуванням.`,
    characteristics: {
      'Матеріал': 'Алюмінієва стрічка 25 мм',
      'Система': 'Venus (Isolite)',
      'Керування': 'Монокомандний ланцюжок',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-741',
    slug: 'rulonni_iz_zakrytoyu_systemoyu_len_0881',
    title: 'Рулонні штори із закритою системою Len 0881',
    sku: 'CS-LEN-0881',
    category_slug: 'zakryta-sistema',
    subcategory_slug: 'rulonni_zakritaya_sistema',
    base_price: 559,
    old_price: 690,
    price_unit: 'грн',
    min_width: 25,
    max_width: 180,
    min_height: 30,
    max_height: 240,
    base_width: 50,
    base_height: 140,
    price_per_sqm: 780,
    fabric: 'Len Закрита система',
    texture: 'Лляна фактура',
    blackout_percent: 50,
    color_name: 'Бежевий льон',
    color_hex: '#C8AD8D',
    available_colors: [
      { id: 'ccl1', name: 'Бежевий', code: 'CS-0881', hex: '#C8AD8D', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg' },
      { id: 'ccl2', name: 'Білий', code: 'CS-0880', hex: '#FFFFFF', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg' },
      { id: 'ccl3', name: 'Капучино', code: 'CS-0885', hex: '#8B7355', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/rb-len-7439-800x800.jpg' },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/rb-len-7439-800x800.jpg',
    ],
    is_popular: true,
    is_new: false,
    is_offer_of_day: false,
    in_stock: true,
    rating: 4.9,
    reviews_count: 8,
    destinations: ['v-spalnju', 'na-kuhnju', 'v-detskuju', 'na-balkon'],
    description: `Закрита касетна система Uni з алюмінієвим коробом та П-подібними направляючими.`,
    characteristics: {
      'Система': 'Закрита касета Uni-1 / Uni-2',
      'Матеріал короба': 'Алюміній',
      'Тканина': 'Len',
      'Затемнення': '50%',
      'Гарантія': '12 місяців',
    },
  },
  {
    id: 'prod-1656',
    slug: 'plise_duo_ecoro_graphite',
    title: 'Штори Плісе Duo Ecoro Graphite PL-502',
    sku: 'PL-502',
    category_slug: 'shtori',
    subcategory_slug: 'plise',
    base_price: 1199,
    old_price: 1390,
    price_unit: 'грн',
    min_width: 20,
    max_width: 160,
    min_height: 30,
    max_height: 220,
    base_width: 50,
    base_height: 130,
    price_per_sqm: 1750,
    fabric: 'Плісе Duo стільникове',
    texture: 'Плісирована фактура 20мм',
    blackout_percent: 80,
    color_name: 'Graphite',
    color_hex: '#3E424B',
    available_colors: [
      { id: 'cpl1', name: 'Graphite', code: 'PL-502', hex: '#3E424B', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/%20%2012%20123123/plicce/graphite-318x480.png' },
      { id: 'cpl2', name: 'White Silk', code: 'PL-501', hex: '#F7F7F7', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg' },
      { id: 'cpl3', name: 'Sand Cream', code: 'PL-503', hex: '#E7D9C3', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg' },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/%20%2012%20123123/plicce/graphite-318x480.png',
    images: [
      'https://manov.com.ua/image/cache/catalog/%20%2012%20123123/plicce/graphite-318x480.png',
      'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
    ],
    is_popular: true,
    is_new: true,
    is_offer_of_day: false,
    in_stock: true,
    rating: 5.0,
    reviews_count: 4,
    destinations: ['na-kuhnju', 'v-spalnju', 'v-gostinnuju', 'na-mansardu'],
    description: `Штори Плісе Duo з можливістю відкривання як зверху вниз, так і знизу вгору.`,
    characteristics: {
      'Тип тканини': 'Плісе з сотовою структурою (Duo)',
      'Ширина складки': '20 мм',
      'Затемнення': '80%',
      'Гарантія': '18 місяців',
    },
  },
  {
    id: 'prod-1608',
    slug: 'vertykalni_zhalyuzi_127mm_line-6',
    title: 'Вертикальні жалюзі 127мм Line Сірий V-8013',
    sku: 'V-8013',
    category_slug: 'zhaluzi',
    subcategory_slug: 'vertikalnie_zhaluzi',
    base_price: 499,
    old_price: 580,
    price_unit: 'грн',
    min_width: 50,
    max_width: 400,
    min_height: 50,
    max_height: 400,
    base_width: 100,
    base_height: 180,
    price_per_sqm: 450,
    fabric: 'Line 127 мм',
    texture: 'Рельєфна тканинна',
    blackout_percent: 60,
    color_name: 'Сірий',
    color_hex: '#8C9298',
    available_colors: [
      { id: 'cv1', name: 'Сірий', code: 'V-8013', hex: '#8C9298', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/%20%2012%20123123/vertikalni/8013-318x480.jpg' },
      { id: 'cv2', name: 'Бежевий', code: 'V-8010', hex: '#D2B48C', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg' },
      { id: 'cv3', name: 'Блакитний', code: 'V-8015', hex: '#87CEEB', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg' },
      { id: 'cv4', name: 'Білий', code: 'V-8001', hex: '#FFFFFF', inStock: true, image: 'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg' },
    ],
    main_image: 'https://manov.com.ua/image/cache/catalog/%20%2012%20123123/vertikalni/8013-318x480.jpg',
    images: [
      'https://manov.com.ua/image/cache/catalog/%20%2012%20123123/vertikalni/8013-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/roller-blind/close-system/cs-rb-len-0881-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/day-night/akvarel-vn-1208-318x480.jpg',
      'https://manov.com.ua/image/cache/catalog/%20жалюзи%20/12%20Белые%20/900-318x480.jpg',
    ],
    is_popular: true,
    is_new: true,
    is_offer_of_day: false,
    in_stock: true,
    rating: 4.8,
    reviews_count: 6,
    destinations: ['v-ofis', 'v-gostinnuju', 'na-balkon'],
    description: `Тканинні вертикальні жалюзі з ламелями 127 мм. Оптимальне рішення для великих віконних прорізів.`,
    characteristics: {
      'Ширина ламелі': '127 мм',
      'Тканина': 'Line',
      'Колір': 'Сірий',
      'Гарантія': '12 місяців',
    },
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-767',
    author_name: 'Оксана Мельник',
    city: 'Київ',
    rating: 5,
    comment: 'Замовляли штори Len на всі вікна в трикімнатну квартиру. Якість тканини чудова, розміри підійшли міліметр у міліметр! Встановили самі за інструкцією за півгодини.',
    created_at: '2026-05-12T14:30:00Z',
  },
];

export const CITIES_LIST = [
  { name: 'Дніпро', slug: 'dnipro' },
  { name: 'Київ', slug: 'kyiv' },
  { name: 'Харків', slug: 'kharkiv' },
  { name: 'Одеса', slug: 'odesa' },
  { name: 'Львів', slug: 'lviv' },
  { name: 'Запоріжжя', slug: 'zaporizhzhia' },
  { name: 'Кривий Ріг', slug: 'kryvyi-rih' },
  { name: 'Кам\'янське', slug: 'kamianske' },
  { name: 'Павлоград', slug: 'pavlohrad' },
  { name: 'Нікополь', slug: 'nikopol' },
  { name: 'Полтава', slug: 'poltava' },
  { name: 'Черкаси', slug: 'cherkasy' },
  { name: 'Вінниця', slug: 'vinnytsia' },
  { name: 'Миколаїв', slug: 'mykolaiv' },
];

export const FAQ_ITEMS = [
  {
    question: 'Як правильно заміряти вікно для замовлення ролет або жалюзі?',
    answer: 'Для відкритої системи виміряйте ширину скла з урахуванням штапиків та висоту всієї рухомої стулки. Детальна покрокова інструкція є в розділі "Замір".',
  },
  {
    question: 'Скільки часу займає виготовлення замовлення?',
    answer: 'Стандартний термін виготовлення на нашому заводі в Дніпрі становить 2-4 робочих дні з моменту підтвердження замовлення.',
  },
  {
    question: 'Якими службами здійснюється доставка по Україні?',
    answer: 'Ми відправляємо вироби Новою Поштою по всій Україні (у відділення, поштомати або кур\'єром за адресою). Всі посилки надійно упаковуються в тубуси чи захисний картон.',
  },
  {
    question: 'Чи надається гарантія на вироби та механізми?',
    answer: 'Так, на всі наші сонцезахисні системи та механізми Besta надається офіційна гарантія виробника 12 місяців.',
  },
];
